name: manual and depends jobs
on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: manual job
        run: echo "Manual job"

  depend-job:
    runs-on: ubuntu-latest
    needs: manual-job
    steps:
      - name: depend job
        run: echo "Job dépendant."